#!/bin/sh -ex
set -e

if [ "$1" = "configure" ]; then
    # Enable and start the service
    systemctl daemon-reload
    systemctl enable mydaemon.service
    systemctl start mydaemon.service
fi

#DEBHELPER#
